### PR TITLE
Update Workspace template from OSGi R7 to R8

### PR DESCRIPTION
**Pull request by chrisrueger**
As suggested in https://github.com/bndtools/bndtools.workspace.min/pull/11#issuecomment-1832442153  by @scottslewis  we up this repo to OSGi R8 and base it on the files of bndtools.workspace.min initially

This may not be the final solution but at least a first step to have an OSGi R8 environment, so that templates may build upon that.

## How  to test this?

This is the place where I need support to verify if we are satisfied with result, or what needs to be changed / added.

- Go to Eclipse Preferences / BndTools / Workspace Template
- Remove the Github repositories (just for testing)
image

- Add this current repo  to "Raw Git Clone URLs" (`https://github.com/chrisrueger/workspace.git` and branch `origin/R7-to-R8`)

- Click Apply and Close
- Go to File / New / Bnd OSGi Workspace
image

- Choose new Workspace or update the current one and Click next
image

- Select the template from the repo you just entered above

image

- when asked to Switch to the Bnd Perpective say "Yes" or manually change there.

### CODE REVIEW

**Comment by chrisrueger** [comment]
@pkriens Could you give me some intro into the templates `.jar` file in https://github.com/chrisrueger/workspace/tree/R7-to-R8/cnf/templates/org.bndtools.templates.osgi 

Where does it come from?

**Comment by chrisrueger** [comment]
Since we want to remove this workspace (see https://github.com/bndtools/bnd/pull/6164) and only keep https://github.com/bndtools/bndtools.workspace.min/ I am closing this.

@pkriens just FYI

**Comment by scottslewis** [comment]
@chrisrueger doesn't that mean that all <= 7.0 versions of bndtools...when using this template...will stay on OSGi R7?   If so, I'm not challenging that decision...I'm just wondering if that has been explicitly discussed.

**Comment by chrisrueger** [comment]
> @chrisrueger doesn't that mean that all <= 7.0 versions of bndtools...when using this template...will stay on OSGi R7? 

Hi @scottslewis ,
yes I think that assumption is correct. for `<=7.0` it would be as it is right now with the current 7.0. release. 

As far as I understand the workspace templates, they are just a bunch of files (build.bnd + .mvn repo definitions) which are "copied" to the `/cnf` folder of the workspace when it is created (and pulled directly from this github repo here at the moment you create the workspace) and remain there. From that moment the "thing" which was once a _workspace template_ starts a live of its own.

In https://github.com/bndtools/bnd/pull/6164 I just removed this specific workspace template here from the list of available templates which is presented to you to choose from. So this template here would not be available in the list of >= 7.1. 

If somebody still wants to use that template I think even in `>=7.1` one would be able to add it to the list of `Raw Git clone Urls` manually - this repo will stay:
image 

> if that has been explicitly discussed.

"explicitly discussed"...well.... I wouldn't put my hand in the fire for it 😄  but we could have this discussion now. 

Let me know

**Comment by scottslewis** [comment]
> > @chrisrueger doesn't that mean that all <= 7.0 versions of bndtools...when using this template...will stay on OSGi R7?
> 
> Hi @scottslewis , yes I think that assumption is correct. for `<=7.0` it would be as it is right now with the current 7.0. release.
> 
> As far as I understand the workspace templates, they are just a bunch of files (build.bnd + .mvn repo definitions) which are "copied" to the `/cnf` folder of the workspace when it is created (and pulled directly from this github repo here at the moment you create the workspace) and remain there. From that moment the "thing" which was once a _workspace template_ starts a live of its own.
> 
> In [bndtools/bnd#6164](https://github.com/bndtools/bnd/pull/6164) I just removed this specific workspace template here from the list of available templates which is presented to you to choose from. So this template here would not be available in the list of >= 7.1.

My expectation matches all of what you say above.

> 
> If somebody still wants to use that template I think even in `>=7.1` one would be able to add it to the list of `Raw Git clone Urls` manually - 

Yes that was my assumption too.  IMHO it might be worthwhile to put something in the documentation...e.g. in the updates file for 7.1 along the lines of what you say above...i.e. that if users wish to continue to use the bndtools.workspace template (R7) then then can easily do so as you describe.

<stuff deleted>
> 
> "explicitly discussed"...well.... I wouldn't put my hand in the fire for it 😄 but we could have this discussion now.

I guess we just did.  I was trying to make sure that it was clear to all what existing bndtools <7.0 users would experience (R7 from bndtools.workspace and R8 [I think] for bndtools.workspace.min), and what people transitioning from 7.0 to 7.1 would experience ('why is bndtools.workspace missing now?  I just used it in 7.0').

Thanks.

**Comment by chrisrueger** [comment]
ok, great thanks for the feedback @scottslewis 

> it might be worthwhile to put something in the documentation...e.g. in the updates file for 7.1 along the lines of what you say above...i.e. that if users wish to continue to use the bndtools.workspace template (R7) then then can easily do so as you describe.

I added something to the section here https://github.com/bndtools/bnd/wiki/Changes-in-7.1.0#templates

**Pull request closed without merging**
