### PR TITLE
Better .gitignore

### PR DESCRIPTION
**Pull request by vorburger**
Please double check & confirm that ignoring cnf/templates/ is fine;
those appear to be downloaded, so doesn't need to go into SCM, right?

### CODE REVIEW

**Comment by seanbright** [comment]
No, cnf/templates is a LocalIndexedRepo, so nothing is downloaded.

**Comment by vorburger** [comment]
@seanbright just to be sure we don't misunderstand each other - so cnf/templates/ should not be on .gitignore then, right? Everything else proposed here apart from cnf/templates/ OK for you?

**Comment by seanbright** [comment]
@vorburger, `cnf/templates` should not be in `.gitignore`. I don't know enough about what files should be and should not be ignored to say that the rest of the PR looks good. I'll have to defer to someone else.

**Comment by bjhargrave** [comment]
I don't see this as a useful change. It incorrectly deletes the cnf/.project file (cnf is a project). Bndtools will create .gitignore file in each project created. So we do not need a root .gitignore which covers other projects.

So I suggest we close this PR.

**Comment by vorburger** [comment]
> cnf/templates should not be in .gitignore

fixed now

> incorrectly deletes the cnf/.project file (cnf is a project)

fixed now for cnf/.project. - For other projects (your bundles), keeping Eclipse .project & .classpath in SCM is a known PITA (Eclipse re-orders content), and current best practice is to let the build tool create these. Your Gradle set-up actually already does this nicely and it works great.

>  So we do not need a root .gitignore which covers other projects.

Sure you do, because this change amends other things missing from the .gitignore

> So I suggest we close this PR.

And I suggest that you re-review this, let me know if anything else is wrong with it, as in our successful collaboration above, giving me an opportunity to re-amend anything else needed, and then merge this PR.

**Comment by bjhargrave** [comment]
> incorrectly deletes the cnf/.project file (cnf is a project)
> 
> fixed now for cnf/.project. - For other projects (your bundles), keeping Eclipse .project & .classpath in SCM is a known PITA (Eclipse re-orders content), and current best practice is to let the build tool create these. Your Gradle set-up actually already does this nicely and it works great.
> 

There is no need for eclipse to modify the .project and .classpath files in a bndtools project. All the classpath information in a bndtools project should be in the bnd.bnd file's -buildpath instruction. Thus once the .classpath is created by the project wizard, it will rarely change. 

>     So we do not need a root .gitignore which covers other projects.
> 
> Sure you do, because this change amends other things missing from the .gitignore

No. The project wizards for bndtools create projects with the proper .gitignore for that project. So we do not want the root .gitignore to conflict/interfere with that.

> 
>     So I suggest we close this PR.
> 
> And I suggest that you re-review this, let me know if anything else is wrong with it, as in our successful collaboration above, giving me an opportunity to re-amend anything else needed, and then merge this PR.

So I still do not see the need for this PR and recommend closing it.

**Comment by bjhargrave** [comment]
Closing.

**Pull request closed without merging**
