### PR TITLE
Added org.osgi.annotation.bundle to maven repo as described by

### PR DESCRIPTION
**Pull request by scottslewis**
Added org.osgi.annotation.bundle to maven repo as described by issue #17 

https://github.com/bndtools/workspace/issues/17

### CODE REVIEW

**Comment by scottslewis** [comment]
@pkriens this is asking for a maintainer to approve before running workflow actions

**Comment by kriegfrj** [comment]
> @pkriens this is asking for a maintainer to approve before running workflow actions

I approved it,  @scottslewis - looks like there was a failure, I haven't investigated...

**Comment by scottslewis** [comment]
Hi @kriegfrj and @pkriens    It seems that gradle is configured to use java 8 for the build action and so was failing (on linux) with

* What went wrong:
java.lang.UnsupportedClassVersionError: aQute/bnd/gradle/BndWorkspacePlugin has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> aQute/bnd/gradle/BndWorkspacePlugin has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0

I added a commit to change the gradle java version to '17' but I don't know if that will work for this repo+action configuration...and that's what's now above with 1 workflow awaiting approval.   

If some other version between 8 and 17 is what's needed for gradle then I would appreciate setting the necessary value before letting the workflow above go forward.

Thanks.

**Comment by kriegfrj** [comment]
> Hi @kriegfrj and @pkriens It seems that gradle is configured to use java 8 for the build action and so was failing (on linux) with
> 
> * What went wrong:
>   java.lang.UnsupportedClassVersionError: aQute/bnd/gradle/BndWorkspacePlugin has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> 
> > aQute/bnd/gradle/BndWorkspacePlugin has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> 
> I added a commit to change the gradle java version to '17' but I don't know if that will work for this repo+action configuration...and that's what's now above with 1 workflow awaiting approval.
> 
> If some other version between 8 and 17 is what's needed for gradle then I would appreciate setting the necessary value before letting the workflow above go forward.
>

It looks like it's using the snapshot versions from the Bnd repo, so for the latest 7.0 snapshot Java 17 will be required (class file version 61 corresponds to Java 17). I have approved your workflow and it looks like it has already passed. :+1:

**Comment by kriegfrj** [comment]
@scottslewis, thanks for this. I am happy but think we just need to tidy up the PR a bit.

I think changing the Java version to 17 is a pretty significant change and probably not one we should sneak in stealthily under the cover of another PR. Are you up for making a separate PR for that one?

If you could then remove those extraneous whitespace/build-triggering commits from what is left and rebase onto the other PR, I can merge both (unless @pkriens objects).

**Pull request closed without merging**
