### PR TITLE
Added org.osgi.annotation.bundle:2.0.0 to central.maven file to satisfy issue #17

### PR DESCRIPTION
**Pull request by scottslewis**
https://github.com/bndtools/workspace/issues/17

### CODE REVIEW

**Comment by kriegfrj** [comment]
Thanks @scottslewis! Now that I have merged #19, do you think you could rebase on master and re-push? I think then we'll be good to merge.

**Comment by scottslewis** [comment]
@kriegfrj I've rebased on merged #19 and now checks are passing

**Comment by scottslewis** [comment]
@kriegfrj @pkriens I think this is ready to merge if you please.

**Comment by scottslewis** [comment]
Please see pr #21 .   

@kriegfrj @pkriens  two questions:

1) Can I get added on as a bndtools committer?   My desire/intention is to continue to add onto the new service wizards and contributing bug reports and fixes.  Doing things this way (fork) is very cumbersome.

2) I have an Eclipse plugin that is a ECF remote-services-specific enhancement (As it is now it provides some ECF-remote services dependent OSGi service wizards...for creating a grpc-based, jaxrs-based, other remote services.   I would like to make distribution of this plugin as easy as possible when bndtools 7 comes out, but afaik there is not any bndtools-based plugin repo/repos/composite, etc.   Any suggestions?

**Comment by laeubi** [comment]
> I have an Eclipse plugin that is a ECF remote-services-specific enhancement (As it is now it provides some ECF-remote services dependent OSGi service wizards...for creating a grpc-based, jaxrs-based, other remote services. I would like to make distribution of this plugin as easy as possible when bndtools 7 comes out, but afaik there is not any bndtools-based plugin repo/repos/composite, etc. Any suggestions?

Usually you build a p2-site upload it somewhere (you can even deploy to maven central) and share the link with your users so the can install it with the update-software dialog of eclipse.

**Comment by pkriens** [comment]
@scottslewis any reason you closed it?

**Comment by kriegfrj** [comment]
> @scottslewis any reason you closed it?

It was superseded by #21 and #22.

**Comment by scottslewis** [comment]
@laeubi 

> 
> Usually you build a p2-site upload it somewhere (you can even deploy to maven central) and share the link with your users so the can install it with the update-software dialog of eclipse.

Yes thanks.

I've already done this (built p2-site).   My question is focused on whether there is any repos/location/mktplace...whatever you want to call it...that is specifically for bndtools-dependent plugins/enhancements (and more precisely bndtools users).

I have/know I already have access to deployment via:

1) marketplace.eclipse.com  (ECF project)
2) download.eclipse.org (ECF project)
3) github.com/ECF (ECF project)

However, this plugin depends specifically upon bndtools 7...to provide remote-services-specific (remote) service wizards, some distribution-provider-specific bndtools enhancements (e.g. very simple grpc protofile editor) and will eventually have more bndtools-specific remote service support.     

My current path is to use some or all of 1-3 above, but since this new plugin is dependent specifically on bndtools 7 I wanted to know if there is some way to make known to bndtools users...either through mktplace or docs...I would like to use whatever is available as well.   And since EF doesn't really pay much marketing attention to either ECF or Bndtools (afaict) I thought I would ask :).

**Comment by pkriens** [comment]
@scottslewis you closed this issue, do you still want to be a committer? I do not get any objections so I am ok

**Comment by scottslewis** [comment]
@pkriens yeah I'll be committer thanks.

**Pull request closed without merging**
